export const coreFullNameMap = {
  a5200: 'a5200',
  fbneo: 'FinalBurn Neo',
  fceumm: 'FCEUmm',
  gearboy: 'Gearboy',
  genesis_plus_gx: 'Genesis Plus GX',
  mednafen_lynx: 'Beetle Lynx',
  mednafen_vb: 'Beetle VB',
  mednafen_wswan: 'Beetle WonderSwan',
  mednafen_ngp: 'Beetle NeoPop',
  mgba: 'mGBA',
  mupen64plus_next: 'Mupen64Plus-Next',
  nestopia: 'Nestopia',
  pcsx2: 'pcsx2',
  picodrive: 'PicoDrive',
  prosystem: 'ProSystem',
  snes9x: 'Snes9x',
  stella2014: 'Stella 2014',
}
